# Generated by Django 5.0.1 on 2024-02-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
    ]
